services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: false
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src:z
      - "./Voicy_Why are you gae_.mp3:/app/sounds/test.mp3:ro,z"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio

  frontend:
    build: ./frontend
    env_file:
      - path: ./.env
        required: false
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src:z
    environment:
      - HOST=0.0.0.0
      - PORT=3000
