/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSoundsRouteImport } from './routes/_app/sounds'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppAirRaidRouteImport } from './routes/_app/air-raid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSoundsRoute = AppSoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAirRaidRoute = AppAirRaidRouteImport.update({
  id: '/air-raid',
  path: '/air-raid',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/air-raid': typeof AppAirRaidRoute
  '/events': typeof AppEventsRoute
  '/profile': typeof AppProfileRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/sounds': typeof AppSoundsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/air-raid': typeof AppAirRaidRoute
  '/events': typeof AppEventsRoute
  '/profile': typeof AppProfileRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/sounds': typeof AppSoundsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/air-raid': typeof AppAirRaidRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sounds': typeof AppSoundsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/air-raid'
    | '/events'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/sounds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/air-raid'
    | '/events'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/sounds'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/air-raid'
    | '/_app/events'
    | '/_app/profile'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/sounds'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sounds': {
      id: '/_app/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof AppSoundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/air-raid': {
      id: '/_app/air-raid'
      path: '/air-raid'
      fullPath: '/air-raid'
      preLoaderRoute: typeof AppAirRaidRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAirRaidRoute: typeof AppAirRaidRoute
  AppEventsRoute: typeof AppEventsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSoundsRoute: typeof AppSoundsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAirRaidRoute: AppAirRaidRoute,
  AppEventsRoute: AppEventsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSoundsRoute: AppSoundsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
